#!/usr/bin/env python3

"""Utility to create a PostgreSQL password hash for a user"""

import argparse
import hashlib

parser = argparse.ArgumentParser()
parser.add_argument("user", help="Login name of user")
parser.add_argument("password", help="Password of user")
args = parser.parse_args()

user = bytes(args.user, 'ascii')
password = bytes(args.password, 'ascii')

print('md5' + hashlib.md5(password + user).hexdigest())
